### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by matt-8319** [jborean93/AmsiProvider#1]
HI,

Great work!

I am trying to replicate your results on Win 10 19041. Assembly builds fine and registers ok. I can see the entries in the registry. I have manually called the AMSI dll scan in another project as well as your powershell example. However I get no output at all. There does not appear to be anything in the event logs.

I have tried signing with an EV cert and enable test signing on my machine, still nothing.

Any tips?

Thanks!

**Comment by jborean93** [comment]
It could be a few things, I've not tried that Windows 10 build. A few things you can check

+ Make sure that the directory the dll is registered with is writable by the user sending the AMSI commands
+ Try out the new `AmsiClient.exe` that I've just commited which will rule out PowerShell
+ Try adjusting the code so that it uses `Providers` and not `Providers2` https://github.com/jborean93/AmsiProvider/blob/af36f1a317087fbc43486b33d4dfe8243900ea83/src/AmsiProvider/DllRegistration.cs#L31-L44

I've just pushed a commit that adds the ability to log the AMSI data to stdout by creating the config file

```powershell
Set-Content .\bin\AmsiProvider\AmsiProvider.config.json (ConvertTo-Json @{
    LogPath = 'stdout'
})
...
```

You can use this to test out the log file permission issue as it'll write to the console of the process instead of trying to use the log file.

**Comment by matt-8319** [comment]
Thanks for your help. I changed the registration from Providers2 to Providers and it is now working.

There is an issue with the logging FileStream though. When the provider is loaded in the space of each process, the filestream is locked exclusively by the first process which opens the file. Subsequent processes can therefore not write to the file.

**Comment by jborean93** [comment]
> Thanks for your help. I changed the registration from Providers2 to Providers and it is now working.

I'll have to spend some time to figure out when `Providers2` was added. The [IAntimalwareProvider2](https://learn.microsoft.com/en-us/windows/win32/api/amsi/nn-amsi-iantimalwareprovider2) states it is supported since Windows 10 and Server 2016 which is based on an earlier Win 10 build but maybe that's just not true. I'll at least add some env var and documentation saying you can set this to load it as a provider 1 COM server which doesn't support `Notify` but will work on older hosts.

> When the provider is loaded in the space of each process, the filestream is locked exclusively by the first process which opens the file

I thought I opened it with `FileShare.ReadWrite` but you are correct in that it is only opening it with `Read` share rights. I'll update it with `ReadWrite` but add a caveat in the docs that it might clobber the entries if multiple processes try to write at the same time.

You can create an `AmsiProvider.config.json` file next to the `AmsiProvider.dll` registered with the contents of

```json
{
    "StoreByPid": true
}
```

This will have the provider log the data in a file per process, the log filename will now be `AmsiProvider.$pid.log` where `$pid` is the process id of what calling AMSI.

Thanks for trying it out and sharing your feedback!
